#![allow(dead_code)]
#[derive(Debug, PartialEq)]
pub enum KernelFunction {
	Open,
	Lseek,
	Read,
	Write,
	Close,
	Ioctl,
	Exit,
	Isatty,
	Getc,
	Putc,
	Setjmp,
	Longjmp,
	Memcpy,
	Memset,
	Memmove,
	Memcmp,
	Memchr,
	Rand,
	Srand,
	Qsort,
	Malloc,
	Free,
	Lsearch,
	Bsearch,
	Calloc,
	Realloc,
	InitHeap,
	_Exit,
	GetChar,
	PutChar,
	Gets,
	Puts,
	Printf,
	SystemErrorUnresolvedException,
	LoadTest,
	Load,
	Exec,
	FlushCache,
	InitA0B0C0Vectors,
	GpuDw,
	GpuSendDma,
	SendGP1Command,
	GpuCw,
	GpuCwp,
	SendGpuLinkedList,
	GpuAbortDma,
	GetGpuStatus,
	GpuSync,
	SystemError,
	LoadExec,
	GetSysSp,
	_96Init,
	_BuInit,
	_96Remove,
	DevTtyInit,
	DevTtyOpen,
	DevTtyInOut,
	DevTtyIoctl,
	DevCdOpen,
	DevCdRead,
	DevCdClose,
	DevCdFirstFile,
	DevCdNextFile,
	DevCdChdir,
	DevCardOpen,
	DevCardRead,
	DevCardWrite,
	DevCardClose,
	DevCardFirstfile,
	DevCardNextfile,
	DevCardErase,
	DevCardUndelete,
	DevCardFormat,
	DevCardRename,
	CdAsyncSeekL,
	CdAsyncGetStatus,
	CdAsyncReadSector,
	CdAsyncSetMode,
	CdromIoIrqFunc1,
	CdromDmaIrqFunc1,
	CdromIoIrqFunc2,
	CdromDmaIrqFunc2,
	CdromGetInt5errCode,
	CdInitSubFunc,
	AddCDROMDevice,
	AddMemCardDevice,
	AddDuartTtyDevice,
	AddNullconDriver,
	SetConf,
	GetConf,
	SetCdromIrqAutoAbort,
	SetMem,
	_Boot,
	EnqueueCdIntr,
	DequeueCdIntr,
	CdGetLbn,
	CdReadSector,
	CdGetStatus,
	BufsCb0,
	BufsCb1,
	BufsCb2,
	BufsCb3,
	_CardInfo,
	_CardLoad,
	_CardAuto,
	BufsCb4,
	CardWriteTest,
	IoabortRaw,
	GetSystemInfo,
	AllocKernelMemory,
	FreeKernelMemory,
	InitTimer,
	GetTimer,
	EnableTimerIrq,
	DisableTimerIrq,
	RestartTimer,
	DeliverEvent,
	OpenEvent,
	CloseEvent,
	WaitEvent,
	TestEvent,
	EnableEvent,
	DisableEvent,
	OpenTh,
	CloseTh,
	ChangeTh,
	JumpTo00000000,
	InitPAD2,
	StartPAD2,
	StopPAD2,
	PadInit2,
	PadDr,
	ReturnFromException,
	ResetEntryInt,
	HookEntryInt,
	UnDeliverEvent,
	Cd,
	Format,
	FirstFile2,
	NextFile,
	Rename,
	Erase,
	Undelete,
	AddDrv,
	DelDrv,
	PrintInstalledDevices,
	InitCARD2,
	StartCARD2,
	StopCARD2,
	_CardInfoSubfunc,
	_CardWrite,
	_CardRead,
	_NewCard,
	Krom2RawAdd,
	Krom2Offset,
	_GetErrno,
	_GetError,
	GetC0Table,
	GetB0Table,
	_CardChan,
	TestDevice,
	ChangeClearPAD,
	_CardStatus,
	_CardWait,
	EnQueueTimerAndVblankIrqs,
	EnqueueSyscallHandler,
	SysEnqIntRP,
	SysDeqIntRP,
	GetFreeEvCBSlot,
	GetFreeTCBSlot,
	ExceptionHandler,
	InstallExceptionHandlers,
	SysInitMemory,
	SysInitKernelVariables,
	ChangeClearRCnt,
	InitDefInit,
	SetIrqAutoAck,
	InstallDevices,
	FlushStdInOutPut,
	_CdevInput,
	_CdevScan,
	_CircGetc,
	_CircPutc,
	_IoAbort,
	SetCardFindMode,
	KernelRedirect,
	AdjustA0Table,
	GetCardFindMOde,
	NoFunction,
	EnterCriticalSection,
	ExitCriticalSection,
	ChangeThreatSubFunction,
	Unknown
}

impl KernelFunction {
	pub fn a_func(num: u32) -> Self {
		match num {
			0x00 => Self::Open,
			0x01 => Self::Lseek,
			0x02 => Self::Read,
			0x03 => Self::Write,
			0x04 => Self::Close,
			0x05 => Self::Ioctl,
			0x06 => Self::Exit,
			0x07 => Self::Isatty,
			0x08 => Self::Getc,
			0x09 => Self::Putc,
			0x13 => Self::Setjmp,
			0x14 => Self::Longjmp,
			0x2A => Self::Memcpy,
			0x2B => Self::Memset,
			0x2C => Self::Memmove,
			0x2D => Self::Memcmp,
			0x2E => Self::Memchr,
			0x2F => Self::Rand,
			0x30 => Self::Srand,
			0x31 => Self::Qsort,
			0x33 => Self::Malloc,
			0x34 => Self::Free,
			0x35 => Self::Lsearch,
			0x36 => Self::Bsearch,
			0x37 => Self::Calloc,
			0x38 => Self::Realloc,
			0x39 => Self::InitHeap,
			0x3A => Self::_Exit,
			0x3B => Self::GetChar,
			0x3C => Self::PutChar,
			0x3D => Self::Gets,
			0x3E => Self::Puts,
			0x3F => Self::Printf,
			0x40 => Self::SystemErrorUnresolvedException,
			0x41 => Self::LoadTest,
			0x42 => Self::Load,
			0x43 => Self::Exec,
			0x44 => Self::FlushCache,
			0x45 => Self::InitA0B0C0Vectors,
			0x46 => Self::GpuDw,
			0x47 => Self::GpuSendDma,
			0x48 => Self::SendGP1Command,
			0x49 => Self::GpuCw,
			0x4A => Self::GpuCwp,
			0x4B => Self::SendGpuLinkedList,
			0x4C => Self::GpuAbortDma,
			0x4D => Self::GetGpuStatus,
			0x4E => Self::GpuSync,
			0x4F | 0x50 | 0x53 | 0x9A | 0x9B | 0xA1 => Self::SystemError,
			0x51 => Self::LoadExec,
			0x52 => Self::GetSysSp,
			0x54 | 0x71 => Self::_96Init,
			0x55 | 0x70 => Self::_BuInit,
			0x56 | 0x72 => Self::_96Remove,
			0x5B => Self::DevTtyInit,
			0x5C => Self::DevTtyOpen,
			0x5D => Self::DevTtyInOut,
			0x5E => Self::DevTtyIoctl,
			0x5F => Self::DevCdOpen,
			0x60 => Self::DevCdRead,
			0x61 => Self::DevCdClose,
			0x62 => Self::DevCdFirstFile,
			0x63 => Self::DevCdNextFile,
			0x64 => Self::DevCdChdir,
			0x65 => Self::DevCardOpen,
			0x66 => Self::DevCardRead,
			0x67 => Self::DevCardWrite,
			0x68 => Self::DevCardClose,
			0x69 => Self::DevCardFirstfile,
			0x6A => Self::DevCardNextfile,
			0x6B => Self::DevCardErase,
			0x6C => Self::DevCardUndelete,
			0x6D => Self::DevCardFormat,
			0x6E => Self::DevCardRename,
			0x78 => Self::CdAsyncSeekL,
			0x7C => Self::CdAsyncGetStatus,
			0x7E => Self::CdAsyncReadSector,
			0x81 => Self::CdAsyncSetMode,
			0x90 => Self::CdromIoIrqFunc1,
			0x91 => Self::CdromDmaIrqFunc1,
			0x92 => Self::CdromIoIrqFunc2,
			0x93 => Self::CdromDmaIrqFunc2,
			0x94 => Self::CdromGetInt5errCode,
			0x95 => Self::CdInitSubFunc,
			0x96 => Self::AddCDROMDevice,
			0x97 => Self::AddMemCardDevice,
			0x98 => Self::AddDuartTtyDevice,
			0x99 => Self::AddNullconDriver,
			0x9C => Self::SetConf,
			0x9D => Self::GetConf,
			0x9E => Self::SetCdromIrqAutoAbort,
			0x9F => Self::SetMem,

			0xA0 => Self::_Boot,
			0xA2 => Self::EnqueueCdIntr,
			0xA3 => Self::DequeueCdIntr,
			0xA4 => Self::CdGetLbn,
			0xA5 => Self::CdReadSector,
			0xA6 => Self::CdGetStatus,
			0xA7 => Self::BufsCb0,
			0xA8 => Self::BufsCb1,
			0xA9 => Self::BufsCb2,
			0xAA => Self::BufsCb3,
			0xAB => Self::_CardInfo,
			0xAC => Self::_CardLoad,
			0xAD => Self::_CardAuto,
			0xAE => Self::BufsCb4,
			0xAF => Self::CardWriteTest,
			0xB2 => Self::IoabortRaw,
			0xB4 => Self::GetSystemInfo,

			_ => Self::Unknown,
		}
	}

	pub fn b_func(num: u32) -> Self {
		match num {
			0x00 => Self::AllocKernelMemory,
			0x01 => Self::FreeKernelMemory,
			0x02 => Self::InitTimer,
			0x03 => Self::GetTimer,
			0x04 => Self::EnableTimerIrq,
			0x05 => Self::DisableTimerIrq,
			0x06 => Self::RestartTimer,
			0x07 => Self::DeliverEvent,
			0x08 => Self::OpenEvent,
			0x09 => Self::CloseEvent,
			0x0A => Self::WaitEvent,
			0x0B => Self::TestEvent,
			0x0C => Self::EnableEvent,
			0x0D => Self::DisableEvent,
			0x0E => Self::OpenTh,
			0x0F => Self::CloseTh,
			0x10 => Self::ChangeTh,
			0x11 | 0x24..=0x29 | 0x2C..=0x31 => Self::JumpTo00000000,
			0x12 => Self::InitPAD2,
			0x13 => Self::StartPAD2,
			0x14 => Self::StopPAD2,
			0x15 => Self::PadInit2,
			0x16 => Self::PadDr,
			0x17 => Self::ReturnFromException,
			0x18 => Self::ResetEntryInt,
			0x19 => Self::HookEntryInt,
			0x1A..=0x1F | 0x21..=0x23 | 0x2A..=0x2B | 0x52 | 0x5A  => Self::SystemError,
			0x20 => Self::UnDeliverEvent,
			0x32 => Self::Open,
			0x33 => Self::Lseek,
			0x34 => Self::Read,
			0x35 => Self::Write,
			0x36 => Self::Close,
			0x37 => Self::Ioctl,
			0x38 => Self::Exit,
			0x39 => Self::Isatty,
			0x3A => Self::Getc,
			0x3B => Self::Putc,
			0x3C => Self::GetChar,
			0x3D => Self::PutChar,
			0x3E => Self::Gets,
			0x3F => Self::Puts,
			0x40 => Self::Cd,
			0x41 => Self::Format,
			0x42 => Self::FirstFile2,
			0x43 => Self::NextFile,
			0x44 => Self::Rename,
			0x45 => Self::Erase,
			0x46 => Self::Undelete,
			0x47 => Self::AddDrv,
			0x48 => Self::DelDrv,
			0x49 => Self::PrintInstalledDevices,

			0x4A => Self::InitCARD2,
			0x4B => Self::StartCARD2,
			0x4C => Self::StopCARD2,
			0x4D => Self::_CardInfoSubfunc,
			0x4E => Self::_CardWrite,
			0x4F => Self::_CardRead,
			0x50 => Self::_NewCard,
			0x51 => Self::Krom2RawAdd,
			0x53 => Self::Krom2Offset,
			0x54 => Self::_GetErrno,
			0x55 => Self::_GetError,
			0x56 => Self::GetC0Table,
			0x57 => Self::GetB0Table,
			0x58 => Self::_CardChan,
			0x59 => Self::TestDevice,
			0x5B => Self::ChangeClearPAD,
			0x5C => Self::_CardStatus,
			0x5D => Self::_CardWait,

			_ => Self::Unknown
		}
	}

	pub fn c_func(num: u32) -> Self {
		match num {
			0x00 => Self::EnQueueTimerAndVblankIrqs,
			0x01 => Self::EnqueueSyscallHandler,
			0x02 => Self::SysEnqIntRP,
			0x03 => Self::SysDeqIntRP,
			0x04 => Self::GetFreeEvCBSlot,
			0x05 => Self::GetFreeTCBSlot,
			0x06 => Self::ExceptionHandler,
			0x07 => Self::InstallExceptionHandlers,
			0x08 => Self::SysInitMemory,
			0x09 => Self::SysInitKernelVariables,
			0x0A => Self::ChangeClearRCnt,
			0x0B => Self::SystemError,
			0x0C => Self::InitDefInit,
			0x0D => Self::SetIrqAutoAck,
			0x12 => Self::InstallDevices,
			0x13 => Self::FlushStdInOutPut,
			0x15 => Self::_CdevInput,
			0x16 => Self::_CdevScan,
			0x17 => Self::_CircGetc,
			0x18 => Self::_CircPutc,
			0x19 => Self::_IoAbort,
			0x1A => Self::SetCardFindMode,
			0x1B => Self::KernelRedirect,
			0x1C => Self::AdjustA0Table,
			0x1D => Self::GetCardFindMOde,
			0x1E..=0x7F => Self::JumpTo00000000,

			0x80..=0xDD => KernelFunction::b_func(num - 0x80),

			_ => Self::Unknown
		}
	}

	pub fn sys_func(num: u32) -> Self {
		match num {
			0x00 => Self::NoFunction,
			0x01 => Self::EnterCriticalSection,
			0x02 => Self::ExitCriticalSection,
			0x03 => Self::ChangeThreatSubFunction,
			0x04..=0xFFFFFFFF => Self::DeliverEvent,
		}
	}

	pub fn num_args(&self) -> usize {
		match self {
			Self::Open => 2,
			Self::Lseek => 3,
			Self::Read => 3,
			Self::Write => 3,
			Self::Close => 1,
			Self::Ioctl => 3,
			Self::Exit => 1,
			Self::Isatty => 1,
			Self::Getc => 1,
			Self::Putc => 2,
			Self::Setjmp => 1,
			Self::Longjmp => 2,
			Self::Memcpy => 3,
			Self::Memset => 3,
			Self::Memmove => 3,
			Self::Memcmp => 3,
			Self::Memchr => 3,
			Self::Rand => 0,
			Self::Srand => 1,
			Self::Qsort => 4,
			Self::Malloc => 1,
			Self::Free => 1,
			Self::Lsearch => 5,
			Self::Bsearch => 5,
			Self::Calloc => 2,
			Self::Realloc => 2,
			Self::InitHeap => 2,
			Self::_Exit => 1,
			Self::GetChar => 0,
			Self::PutChar => 1,
			Self::Gets => 1,
			Self::Puts => 1,
			Self::Printf => 1,
			Self::SystemErrorUnresolvedException => 0,
			Self::LoadTest => 2,
			Self::Load => 2,
			Self::Exec => 3,
			Self::FlushCache => 0,
			Self::InitA0B0C0Vectors => 0,
			Self::GpuDw => 5,
			Self::GpuSendDma => 5,
			Self::SendGP1Command => 1,
			Self::GpuCw => 1,
			Self::GpuCwp => 2,
			Self::SendGpuLinkedList => 1,
			Self::GpuAbortDma => 0,
			Self::GetGpuStatus => 0,
			Self::GpuSync => 0,
			Self::SystemError => 0,
			Self::LoadExec => 3,
			Self::GetSysSp => 0,
			Self::_96Init => 0,
			Self::_BuInit => 0,
			Self::_96Remove => 0,
			Self::DevTtyInit => 0,
			Self::DevTtyOpen => 3,
			Self::DevTtyInOut => 2,
			Self::DevTtyIoctl => 3,
			Self::DevCdOpen => 3,
			Self::DevCdRead => 3,
			Self::DevCdClose => 1,
			Self::DevCdFirstFile => 3,
			Self::DevCdNextFile => 3,
			Self::DevCdChdir => 1,
			Self::DevCardOpen => 3,
			Self::DevCardRead => 3,
			Self::DevCardWrite => 3,
			Self::DevCardClose => 1,
			Self::DevCardFirstfile => 3,
			Self::DevCardNextfile => 2,
			Self::DevCardErase => 2,
			Self::DevCardUndelete => 2,
			Self::DevCardFormat => 1,
			Self::DevCardRename => 4,
			Self::CdAsyncSeekL => 1,
			Self::CdAsyncGetStatus => 1,
			Self::CdAsyncReadSector => 3,
			Self::CdAsyncSetMode => 1,
			Self::CdromIoIrqFunc1 => 0,
			Self::CdromDmaIrqFunc1 => 0,
			Self::CdromIoIrqFunc2 => 0,
			Self::CdromDmaIrqFunc2 => 0,
			Self::CdromGetInt5errCode => 2,
			Self::CdInitSubFunc => 0,
			Self::AddCDROMDevice => 0,
			Self::AddMemCardDevice => 0,
			Self::AddDuartTtyDevice => 0,
			Self::AddNullconDriver => 0,
			Self::SetConf => 3,
			Self::GetConf => 3,
			Self::SetCdromIrqAutoAbort => 2,
			Self::SetMem => 1,
			Self::_Boot => 0,
			Self::EnqueueCdIntr => 0,
			Self::DequeueCdIntr => 0,
			Self::CdGetLbn => 1,
			Self::CdReadSector => 3,
			Self::CdGetStatus => 0,
			Self::BufsCb0 => 0,
			Self::BufsCb1 => 0,
			Self::BufsCb2 => 0,
			Self::BufsCb3 => 0,
			Self::_CardInfo => 1,
			Self::_CardLoad => 1,
			Self::_CardAuto => 1,
			Self::BufsCb4 => 0,
			Self::CardWriteTest => 1,
			Self::IoabortRaw => 1,
			Self::GetSystemInfo => 1,
			Self::AllocKernelMemory => 1,
			Self::FreeKernelMemory => 1,
			Self::InitTimer => 3,
			Self::GetTimer => 1,
			Self::EnableTimerIrq => 1,
			Self::DisableTimerIrq => 1,
			Self::RestartTimer => 1,
			Self::DeliverEvent => 2,
			Self::OpenEvent => 4,
			Self::CloseEvent => 1,
			Self::WaitEvent => 1,
			Self::TestEvent => 1,
			Self::EnableEvent => 1,
			Self::DisableEvent => 1,
			Self::OpenTh => 3,
			Self::CloseTh => 1,
			Self::ChangeTh => 1,
			Self::JumpTo00000000 => 0,
			Self::InitPAD2 => 4,
			Self::StartPAD2 => 0,
			Self::StopPAD2 => 0,
			Self::PadInit2 => 4,
			Self::PadDr => 0,
			Self::ReturnFromException => 0,
			Self::ResetEntryInt => 0,
			Self::HookEntryInt => 1,
			Self::UnDeliverEvent => 2,
			Self::Cd => 1,
			Self::Format => 1,
			Self::FirstFile2 => 2,
			Self::NextFile => 1,
			Self::Rename => 2,
			Self::Erase => 1,
			Self::Undelete => 1,
			Self::AddDrv => 1,
			Self::DelDrv => 1,
			Self::PrintInstalledDevices => 0,
			Self::InitCARD2 => 1,
			Self::StartCARD2 => 0,
			Self::StopCARD2 => 0,
			Self::_CardInfoSubfunc => 1,
			Self::_CardWrite => 3,
			Self::_CardRead => 3,
			Self::_NewCard => 0,
			Self::Krom2RawAdd => 1,
			Self::Krom2Offset => 1,
			Self::_GetErrno => 0,
			Self::_GetError => 1,
			Self::GetC0Table => 0,
			Self::GetB0Table => 0,
			Self::_CardChan => 0,
			Self::TestDevice => 1,
			Self::ChangeClearPAD => 1,
			Self::_CardStatus => 1,
			Self::_CardWait => 1,
			Self::EnQueueTimerAndVblankIrqs => 1,
			Self::EnqueueSyscallHandler => 1,
			Self::SysEnqIntRP => 2,
			Self::SysDeqIntRP => 2,
			Self::GetFreeEvCBSlot => 0,
			Self::GetFreeTCBSlot => 0,
			Self::ExceptionHandler => 0,
			Self::InstallExceptionHandlers => 0,
			Self::SysInitMemory => 2,
			Self::SysInitKernelVariables => 0,
			Self::ChangeClearRCnt => 2,
			Self::InitDefInit => 1,
			Self::SetIrqAutoAck => 2,
			Self::InstallDevices => 1,
			Self::FlushStdInOutPut => 0,
			Self::_CdevInput => 2,
			Self::_CdevScan => 0,
			Self::_CircGetc => 1,
			Self::_CircPutc => 2,
			Self::_IoAbort => 2,
			Self::SetCardFindMode => 1,
			Self::KernelRedirect => 1,
			Self::AdjustA0Table => 0,
			Self::GetCardFindMOde => 0,
			Self::NoFunction => 0,
			Self::EnterCriticalSection => 0,
			Self::ExitCriticalSection => 0,
			Self::ChangeThreatSubFunction => 1,
			Self::Unknown => 0,
		}
	}
}